config/routes.rb
Rails.application.routes.draw do
  root "todos#index"
  get "/todos", to: "todos#index"
  #get "/todos/:id", to: "todos#show"
  get "/todos/new", to: "todos#new"
  post "/todos", to: "todos#create"
  #resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :Description, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todos_path 
    else 
      render :new, status: :unprocessable_entity
    end
  end
  private
    def todo_params
      params.require(:todo).permit(:Description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Todo List </h1>
<%= form_with model:@todo do |form| %>
    <div>
        <ul>
        <% @todos.each do |todo| %>
            <%= form.check_box :Description %>
            <a href="/todos/<%= todo.id %>">
            <%= todo.Description %> <br>
            </a>
        <% end %>
        </ul>
<%end%>

<%= link_to "New Todos", todos_new_path %>

app/views/todos/new.html.erb
<h1> new todo item </h1>

<%= form_with model:@todo do |form| %>
    <div>
        <%= form.label :Description %> 
        <%= form.text_field :Description %>
    </div>
    <div>
        <br>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/todos/show.html.erb
<h1><%=@todo.Description %></h1>